ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
}

database {
    url = "${?DATABASE_URL}"
    user = "${?DATABASE_USER}"
    password = "${?DATABASE_PASSWORD}"
}

flyway.migrate = ${?FLYWAY_MIGRATE}


